@Sql.SemanticSearch.Api_HostAddress = http://localhost:5266

POST {{Sql.SemanticSearch.Api_HostAddress}}/api/search/
Content-Type: application/json
Accept: application/json

{
  "query": "Find papers on neutrinos",
  "top_k": 3
}

###
