@Sql.SemanticSearch.Api_HostAddress = http://localhost:5266

POST {{Sql.SemanticSearch.Api_HostAddress}}/api/search/
Content-Type: application/json
Accept: application/json

{
  "query": "I am looking for information on Gradient Descent",
  "metadata": "",
  "top_k": 3
}

###
