<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DataIngestion" />
    <PackageReference Include="Microsoft.Extensions.DataIngestion.Markdig" />
    <PackageReference Include="Microsoft.Extensions.DataIngestion.MarkItDown" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Resilience" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sql.SemanticSearch.Core.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sql.SemanticSearch.Shared\Sql.SemanticSearch.Shared.csproj" />
  </ItemGroup>
</Project>
      